name: "ci-test-2312"
on: { push: { branches: [ "**" ], tags: [ "v*" ] } } # use `v0.0.0` tag pattern # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
env: { "IS_CI": true }
jobs:
  "publish-tag": # job id
    if: "github.ref_type == 'tag'" # only run on git tag push
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - { uses: "actions/checkout@v4" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v4", with: { node-version: "20.x" } } # LTS version # https://github.com/actions/setup-node
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN_DR_JS }}" > .npmrc
      - run: npm run script-publish
